<?php
require_once __DIR__ . '/vendor/autoload.php';

require_once('easier.tools.php');
require_once('easier.drupal.php');
require_once('drupal7.php');
require_once('editcol.form_function.php');
require_once('editcol.form_model.php');
require_once('editcol.upload.php');
require_once('editcol.set.php');

require_once('editcol.inc.php');

function editcol_permission() {
  return array(
    'control panel' => array(
      'title' => t('control panel'),
      'description' => t('Can use control panel.'),
    ),
  );
}


function editcol_menu() {

  $items['control_panel'] = array(
    'page callback' => 'control_panel',
    //'access arguments' => array('admin claim'),
    'access arguments' => array('control panel'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/edit/%'] = array(
    'page callback'  => 'collection_edit',
    'page arguments' => array(2),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/delete/%'] = array(
    'page callback'  => 'collection_delete',
    'page arguments' => array(2),
    'access arguments' => array('delete collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/single_upload/finish'] = array(
    'page callback'  => 'collection_single_upload_finish',
    'access arguments' => array('add collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/multiple_upload/finish'] = array(
    'page callback'  => 'collection_multiple_upload_finish',
    'access arguments' => array('add collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/multiple_update/finish'] = array(
    'page callback'  => 'collection_multiple_update_finish',
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );


  // % would be 10001-10100, for example
  $items['action/export/csv/%'] = array(
    'page callback'  => 'export_csv',
    'page arguments' => array(3),
    'access arguments' => array('add collection'),
    'type' => MENU_CALLBACK,
  );

  // % would be a key, like csv_PpQXn7COf
  $items['action/export/csv/unordered/%'] = array(
    'page callback'  => 'export_csv_unordered',
    'page arguments' => array(4),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/pl_upload'] = array(
    'page callback'  => 'collection_pl_upload',
    'access arguments' => array('add collection'),
    'type' => MENU_CALLBACK,
  );

// [[ 更新數位檔 ---------------------------------------------------------------------------------------------------------------------------

  // 選擇更新方式
  $items['collection/update/file/%'] = array(
    'title' => 'Update collection files',
    'description' => 'Update files of a colleciont.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_choose_collection_file_update_way', 3),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  // 全部更新
  $items['collection/update/file/all/%'] = array(
    'page callback'  => 'collection_file_update_all_upload', // 進入 plupload 介面, ALL
    'page arguments' => array(4),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  // 全部更新動作
  $items['collection/all_file_update'] = array(
    'page callback'  => '_collection_all_file_update_form_submit', // 處理 plupload 的上傳, 此時是全部檔案更新。
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  // 個別更新
  $items['collection/update/file/idv/%'] = array(
    'title' => 'Update a collection file',
    'description' => 'Update a file of a collection.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('collection_file_update_idv', 4),  // 進入選擇檔案介面
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  // 單檔上傳
  $items['collection/idv_file_update'] = array(
    'page callback'  => '_collection_idv_file_update_form_action', // 處理 plupload 的上傳, 此時是單一檔案上傳。
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/%/mosaic/file/update/%'] = array(
    //'title' => 'Update a mosaic file of a collection',
    //'description' => 'Update a mosaic file of a collection.',
    'page callback' => 'collection_mosaic_file_update',
    'page arguments' => array(1, 5),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/%/mosaic/file/delete/%'] = array(
    'title' => 'Delete a mosaic file of a collection',
    'description' => 'Delete a mosaic file of a collection.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('collection_mosaic_file_delete', 1, 5),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/%/normal/file/update/%'] = array(
    'title' => 'Update a normal file of a collection',
    'description' => 'Update a normal file of a collection.',
    'page callback' => 'collection_normal_file_update',
    'page arguments' => array(1, 5),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/%/normal/file/delete/%'] = array(
    'title' => 'Delete a normal file of a collection',
    'description' => 'Delete a normal file of a collection.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('collection_normal_file_delete', 1, 5),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['collection/%/normal/file/addmosaic/%'] = array(
    'title' => 'Add a mosaic file for a normal file of a collection',
    'description' => 'Add a mosaic file for a normal file of a collection.',
    'page callback' => 'collection_normal_file_addmosaic',
    'page arguments' => array(1, 5),
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  /*
   * 20151216 批次更新數位檔，以原件典藏編號之 zip 檔更新
   *
   */
  $items['collection/multiple_update'] = array(
    'page callback'  => 'collection_multiple_update',
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  /*
   * 20151216 批次更新數位檔，以原件典藏編號之 zip 檔更新
   *
   */
  $items['collection/multiple_update/finish'] = array(
    'page callback'  => 'collection_multiple_update_finish',
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  // 更新數位檔 ]]--------------------------------------------------------------------------------------------------------------------------


  // [[ 更新影片縮圖 ---------------------------------------------------------------------------------------------------------------------------

  // 2015.08.11 upload video icon file
  $items['collection/upload/video_icons/%'] = array(
    'title' => 'upload video icon',
    'description' => 'upload user custom video icons for a collection.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('icon_upload_form', 3),
    'access arguments' => array('update collection'),
    'type' => MENU_NORMAL_ITEM,
  );
  // 更新影片縮圖 ]]---------------------------------------------------------------------------------------------------------------------------

  // web services

  $items['json/get/form/model/collection'] = array(
    'page callback' => 'json_get_form_model_collection',
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  // 2015.10.05 add new no file collection
  $items['json/new/collection'] = array(
    'page callback' => 'json_edit_collection',
    'access arguments' => array('add collection'),
    'type' => MENU_CALLBACK,
  );

  $items['json/edit/collection'] = array(
    'page callback' => 'json_edit_collection',
    'access arguments' => array('update collection'),
    'type' => MENU_CALLBACK,
  );

  $items['json/delete/collection'] = array(
    'page callback' => 'json_delete_collection',
    'access arguments' => array('delete collection'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


