<?php
require_once 'collpubapi.inc';

function collpubapi_menu() {
  $items['admin/config/coll/public_api'] =
    array(
      'title' => 'Collection Public Api',
      'description' => '',
      'page callback' => 'collapi_admin_page',
      'access arguments' => array('admin collection'),
      'weight' => -3,
    );

  $items['api/getcol'] =
    array(
      'title' => 'collection',
      'description' => 'collection.',
      'page callback' => '_collpubapi_getcol',
      'access arguments' => array('view collection'),
    );
  return $items;
}

function collpubapi_collpubimportfin() {
  //collapi_build_datas();
  //drupal_set_message('api data rebuild');
}

/*
DROP table if exists col_api_data;
CREATE TABLE `col_api_data` (
  `identifier` int(10) unsigned NOT NULL,
  `type` varchar(255) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `icon_info` longtext,
  `thumb` varchar(255) DEFAULT NULL,
  `medium` varchar(255) DEFAULT NULL,
  `text` longtext,
  PRIMARY KEY (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

*/
