<?php
use Drupal\wg\WGEntity;
//require_once('collarchive.xxx.nmth.list.inc');
require_once('collarchive.xxx.nmth.inc');
//require_once('collarchive.xxx.nmth_mm.inc');
//require_once('collarchive.xxx.da.inc');
function _collarchive_drush_xxx() {
  _xx_nmth_metadata();
  //_xx_nmth_metadata_mm();
  //_export_to_dacenter();
  //_xx_nmth_mmlist(); //multi media 清單
  //_xx_nmth_list(); //清單
  //_xx_nmth_csvlist(); //清單

}
